import type { HoldAnnotations } from "enums/hold/holdAnnotations";
import type { AircraftId } from "../aircraftId";
import type { Nullable } from "../utility-types";

export type ApiFlightplan = {
  aircraftId: AircraftId;
  cid: string;
  status: "Proposed" | "Active" | "Tentative";
  assignedBeaconCode: Nullable<number>;
  equipment: string;
  aircraftType: string;
  icaoEquipmentCodes: string;
  icaoSurveillanceCodes: string;
  faaEquipmentSuffix: string;
  speed: number;
  altitude: string;
  departure: string;
  destination: string;
  alternate: string;
  route: string;
  estimatedDepartureTime: number;
  actualDepartureTime: number;
  fuelHours: number;
  fuelMinutes: number;
  hoursEnroute: number;
  minutesEnroute: number;
  pilotCid: string;
  remarks: string;
  holdAnnotations: Nullable<HoldAnnotations>;
};
