export enum DepRowField {
  FID = "FID_DEP_ROW_FIELD",
  P_TIME = "P_TIME_DEP_ROW_FIELD",
  TYPE = "TYPE_DEP_ROW_FIELD",
  ALT = "ALT_DEP_ROW_FIELD",
  CODE = "CODE_DEP_ROW_FIELD",
  ROUTE = "ROUTE_DEP_ROW_FIELD"
}
