export const Tooltips = {
  mca: '"Message Composition Area"\nInput commands here such as:\nUU-calls forward the ACL\nUU D-calls forward the DEP list\nUU C-same as the ACL Clean Up button\nUU AID-selects the aircraft; if not in the EDST, will add the entry\nUU H AID-toggles highlighing for this entry',
  ra: '"Response Area"\nDisplays response to certain commands.',
  acl: '"Aircraft List", Displays active flights projected to transit your airspace (lateral and vertically).\nRW: entry is added when aircraft is 30min or less from the boundary.\nCurrently: displays when aircraft is 100nm or less form the boundary.',
  dep: '"Departure List", Displays all proposed departures\nRW: entry is added if you are the first CTR sector the aircraft will enter.\nCurrently: displays all departures for airports listed as in the jurisdiction of the selected ARTCC.',
  plans: 'Displays the resutls of a submitted trial plan in text format.\nFLID=GREEN, no conflicts detected\nFLID=YELLOW, at least one conflict detected that will bring the aircraft between 6-10 miles of another aircraft\nFLID=RED, at least one conflict detected that will bring the aircraft within 5 miles of another aircraft\n\nNOTE: Conflict Detection is not yet simulated',
  status_active: '[NOT SIMULATED, YET]\nRW: Displays the current status of various systems the EDST connects to.\nvEDST: Misc. Information.',
  status_outage: '[NOT SIMULATED, YET]\nList of inactive/malfunctioning systems.\nList items colored GREEN indicates a previously errored system is not working correctly.',
  plan_options: 'Options for manipulating FP data.\nSelect an aircraft for this menu to become active.',
  plan_options_alt: 'Trial plan or amend assigned altitude.\n\nNOTE: Does not push assignments from vEDST to the controller client or server until we have access to these systems.',
  plan_options_speed: 'Trial plan or amend assigned speed.\n\nNOTE: Does not push assignments from vEDST to the controller client or server until we have access to these systems.',
  plan_options_route: 'Trial plan or amend assigned routing.\n\nNOTE: Does not push assignments from vEDST to the controller client or server until we have access to these systems.',
  plan_options_prev_route: 'Revert to previously assigned routing.\n\nNOTE: Does not push assignments from vEDST to the controller client or server until we have access to these systems.',
  plan_options_stop_probe: 'Stop conflict detection probing for sected aircraft.\n\nNOTE: Conflict Detection not yet simulated.',
  plan_options_trial_restr: 'Trial plan a time/altitude restriction.',
  plan_options_plans: 'View trial plans for the selected aircraft.',
  plan_options_keep: 'Keep the selected aircraft in the list indefinitely;will not grey-out.\nTo remove, select the aircraft>plan options>detele.',
  plan_options_delete: 'Delete the selected aircraft from the list.\nMay be added again via the UU command',
  hold: '"Airborne holding"\nSelect an aircraft for this menu to become active.',
  hold_location: 'Fix over which the aircraft will holding.',
  hold_direction: 'Direction of holding pattern relative to the holding fix.',
  hold_turns: 'Direction of turns in the holding pattern.',
  hold_leg_length: 'Length of legs in the holding pattern.',
  hold_delete_hold_instr: 'Reset the holding fix/dir/turns/legs.',
  hold_efc: '"Expect Further Clearance Time"',
  hold_del_efc: 'When this button is selected, the existing EFC time for the flight is deleted from the input box in the Hold Data Menu.',
  hold_hold_btn: 'Execute/Place in hold.',
  hold_hold_spa_btn: 'Execute/Place in hold and move to Special Positing Area (SPA)',
  sort: 'Set sorting method.\nOrganizes this list in order per the selected sort method.\n\nTIPS:\n-ACL: RW controllers tend to leave this on Sector/NonSector with either Boundary Time or ACID\n\n-DEP list: RW controllers tend to use the Proposed Departure Time (P-Time) however with the nature of the simulated environment, it is suggested to not use this option.',
  sort_acl_sector_non_sector: 'Sorts aircraft first by what sector has track-control for the aircraft; with your sector being above all others.\nThen the system sorts per the selected sort method below.\n\nNOTE: This is not yet simulated, as the system does not know who has track-control for an aircraft. Access to the RADAR client is required for this feature to be simulated.',
  sort_acid: 'Sort alphabetically by callsign.\nAircraft are sorted in the Normal Posting Area in alphanumeric order based on the ACID; Aircraft in the manual positing area are not sorted by this logic, but rather by time of entry into the ACL.',
  sort_boundary_time: 'Sort ACL entries are sorted with the aircraft estimated to cross the sector boundary first at the top of the list.',
  sort_conflict_status: 'Red alerts are displayed at the top of the list, followed by the yellow alerts, and then the airspace alerts\nWithin each alert status group, the order is determined by the alert time with the earliest alert at the top\nConflict free aircraft are sorted at the bottom.\nNOTE: Conflict Detection is not yet simulated',
  sort_conflict_time: 'ACL entries are sorted by conflict alert time, with the entry predicted to have the earliest occurring alert displayed at the top\nConflict free aircraft are sorted at the bottom of the list.\nNOTE: Conflict Detection is not yet simulated',
  sort_destination: 'Sort by destination airport.',
  sort_origin: 'Sort by origin airport.',
  sort_sector_by_sector: 'Sort by the aircraft\'s current sector.\nACL entries are sorted based on the ID of the sector that has track-control\nAircraft under the users control are at the top of the list, followed by aircraft under other sectors control\n\nNOTE: This is not yet simulated, as the system does not know who has track-control for an aircraft. Access to the RADAR client is required for this feature to be simulated',
  sort_p_time: 'Sort by Proposed Departure Time (P-Time)',
  posting_mode: 'Toggles between the automatic and manual posting modes for the ACL\nWhen a posting mode is selected, the title bar changes accordingly\n\nWhen Manual mode is selected, all new ACL entries are placed in the Manual Posting Area in the order in which they are received.',
  template: 'View flight plan template\n\nNOTE: Editing this data is not yet simulated. Access to the RADAR client or FSD is required for this feature to be simulated.',
  acl_clean_up: 'Cleans up the ACL by removing all entries coded gray for deletion.',
  acl_header_pa: 'Toggle number of point outs entries to display.',
  acl_header_type: '',
  acl_header_alt: '',
  acl_header_code: '',
  acl_header_hdg: 'Show/hide assigned heading\n\nNOTE: Does not sync with assignments via the RADAR client until we have access.',
  acl_header_slash: 'Show/hide assigned heading and speed\n\nNOTE: Does not sync with assignments via the RADAR client until we have access.',
  acl_header_spd: 'Show/hide assigned speed\n\nNOTE: Does not sync with assignments via the RADAR client until we have access.',
  acl_N_and_VCI_button: 'Removes the "new (N)" entry indicator and then it will toggle the voice communication indicator (VCI) with further clicks\n\nNOTE: Entry will not grey-out if the VCI is toggled on.\nThe //(AID) command will also toggle the VCI on/off.',
  acl_flight_id: 'Callsign',
  acl_hotbox: '"Hotbox"\nLMB: opens and closes the free-text typing area\nMMB: move to spa\nRMB: toggle highlight',
  acl_type: 'Aircraft Type Identifier',
  acl_alt: 'Assigned Altitude\n\nNOTE: Does not push assignments from vEDST to the controller client or server until we have access to these systems.',
  acl_code: 'Assigned squawk/beacon code\n\nNOTE: This may not match what the aircraft is actually squawking.',
  acl_hdg: 'Assign heading\n\n.NOTE: Does not sync with assignments via the RADAR client until we have access.',
  acl_hdg_amend: 'Assign heading now.\n\nNOTE: Does not sync with assignments via the RADAR client until we have access.',
  acl_hdg_scratchpad: 'Heading planned to assign in future.',
  acl_hdg_turn: 'Incremental left/right turn.\n\nNOTE: Does not sync with assignments via the RADAR client until we have access.',
  acl_hdg_hdg: 'Heading to assign.\n\nNOTE: Does not sync with assignments via the RADAR client until we have access.',
  acl_spd: 'Assign speed.\n\nNOTE: Does not sync with assignments via the RADAR client until we have access.',
  acl_spd_amend: 'Assign speed now.\n\nNOTE: Does not sync with assignments via the RADAR client until we have access.',
  acl_spd_scratchpad: 'Speed planned to assign in future.\n\nNOTE: Does not sync with assignments via the RADAR client until we have access.',
  acl_spd_knots: 'Indicated airspeed\n\nNOTE: Does not sync with assignments via the RADAR client until we have access.',
  acl_spd_mach: 'Mach number.\n\nNOTE: Does not sync with assignments via the RADAR client until we have access.',
  acl_remark_btn: 'LMB: toggle flight plan remarks | RMB: toggle route as displayed on VATSIM',
  acl_route: 'Open route menu',
  dep_header_type: '',
  dep_header_alt: '',
  dep_header_code: '',
  dep_checkmark_N_button: 'Acknowledge flight plan\n\nTIP: Toggle the N to off once you have reviewed the flight plan and made any required changes.',
  dep_flight_id: 'Callsign',
  dep_hotbox: '"Hotbox"\nLMB: opens and closes the free-text typing area.\nMMB: move to spa.\nRMB: toggle highlight.\n\nNOTE: If you highlight, input free-text information in, or place the aircraft into SPA while in the DEP list, it will transfer to the ACL the same way.',
  dep_type: 'Aircraft Type Identifier',
  dep_alt: 'Assigned Altitude',
  dep_code: 'Assigned squawk/beacon code',
  dep_route: 'Open route menu',
  plans_amend: 'Accept trial plan result and send flight plan amendment. Will also copy fix/radial/distance (FRD) the RADAR client until we have access.',
  plans_tools: '[NOT SIMULATED, YET]\nDisplays the Tools Menu\nThe Tools Menu allows the user to select restrictions\nThe difference between the Aircraft List and the Graphic Plan Display Tools Menu from the Plans Display Tools Menu is that the Plans Displays Tools Menu only has one available option, Restrictions.',
  plans_icao: '[NOT SIMULATED, YET]\nDisplays available International Civil Aviation Organization (ICAO) flight data for a selected entry',
  plans_clean_up: 'Cancel and clear all trial plans',
  route_menu_trial_plan: 'Any actions taken while this button is selected will be sent as a trial plan only.\nTo have the action actually submitted, select "Amend" to the right.\n\nNOTE: Does not sync with assignments via the RADAR client until we have access.',
  route_menu_vatsim_logo: 'Toggle the non-formatted route, as seen on VATSIM.\n\nTIP: If you have a route discontinuity [XXX], toggle the VATSIM route to see what the problem is.',
  route_menu_amend: 'Any actions taken while this button is selected will be sent as an actual amendment.\nTo have the action submitted as only a trial plan, select "Trial Plan" to the left.\n\nNOTE: Does not sync with assignments via the RADAR client until we have access.',
  route_menu_frd: 'Current location relative to a predefined reference fix in the fix/radial/distance (FRD) format.\nRMB: copy FRD to clipboard',
  route_menu_route_input: 'Type the route manually here.\n\nNOTE: Does not sync with assignments via the RADAR client until we have access.',
  route_menu_par: '[NOT SIMULATED, YET]\nInclude applicable PAR',
  route_menu_append_star: '[NOT SIMULATED, YET]\nOverride and ignore required PAR/PDAR routing\n\nNOTE: Does not sync with assignments via the RADAR client until we have access.',
  route_menu_append_oplus: '[NOT SIMULATED, YET]\nInhibits ERR application if the box was not previously selected.\n\nNOTE: Does not sync with assignments via the RADAR client until we have access.',
  route_menu_direct_fix: 'Proceed direct to this fix from current location.\nLMS on fix: will copy FRD+remaining route to the clipboard if AMEND is selected in the top right.\n\nNOTE: Does not sync with assignments via the RADAR client until we have access.',
  route_menu_preferred_eligible: 'Show eligible preferred routes based on routing criteria.',
  route_menu_preferred_all: 'Show all known preferred routes, regardless if the aircraft meet the qualifications for the route.',
  route_menu_preferred_route: 'Click to apply this preferred route.\n\nNOTE, this will replace the full route, not append it.',
  route_menu_flight_data: '[NOT SIMULATED, YET]',
  route_menu_prev_route: 'Revert to previously assigned route',
  route_menu_tfm_reroute: '[NOT SIMULATED, YET]',
  alt_menu_trial_plan: 'Trial Plan Only',
  alt_menu_amend: 'Assign Altitude Now',
  alt_menu_t: 'Assign Altitude as Interim'
};
