export const Tooltips = {
  mca:
    '"Message Composition Area"\nInput commands here such as:\nUU-calls forward the ACL\nUU D-calls forward the DEP list\nUU C-same as the ACL Clean Up button\nUU AID-selects the aircraft; if not in the EDST, will add the entry\nUU H AID-toggles highlighting for this entry',
  ra: '"Response Area"\nDisplays response to certain commands.',
  acl:
    '"Aircraft List", Displays active flights projected to transit your airspace (lateral and vertically).\nRW: entry is added when aircraft is 30min or less from the boundary.\nCurrently: displays when aircraft is 100nm or less form the boundary.',
  dep:
    '"Departure List", Displays all proposed departures\nRW: entry is added if you are the first CTR sector the aircraft will enter.\nCurrently: displays all departures for airports listed as in the jurisdiction of the selected ARTCC.',
  plans:
    "Displays the results of a submitted trial plan in text format.\nFLID=GREEN, no conflicts detected\nFLID=YELLOW, at least one conflict detected that will bring the aircraft between 6-10 miles of another aircraft\nFLID=RED, at least one conflict detected that will bring the aircraft within 5 miles of another aircraft\n\nNOTE: Conflict Detection is not yet simulated",
  statusActive: "[NOT SIMULATED, YET]\nRW: Displays the current status of various systems the EDST connects to.\nvEDST: Misc. Information.",
  statusOutage:
    "[NOT SIMULATED, YET]\nList of inactive/malfunctioning systems.\nList items colored GREEN indicates a previously errored system is not working correctly.",
  planOptions: "Options for manipulating FP data.\nSelect an aircraft for this menu to become active.",
  planOptionsAlt:
    "Trial plan or amend assigned altitude.\n\nNOTE: Does not push assignments from vEDST to the controller client or server until we have access to these systems.",
  planOptionsSpeed:
    "Trial plan or amend assigned speed.\n\nNOTE: Does not push assignments from vEDST to the controller client or server until we have access to these systems.",
  planOptionsRoute:
    "Trial plan or amend assigned routing.\n\nNOTE: Does not push assignments from vEDST to the controller client or server until we have access to these systems.",
  planOptionsPrevRoute:
    "Revert to previously assigned routing.\n\nNOTE: Does not push assignments from vEDST to the controller client or server until we have access to these systems.",
  planOptionsStopProbe: "Stop conflict detection probing for selected aircraft.\n\nNOTE: Conflict Detection not yet simulated.",
  planOptionsTrialRestr: "Trial plan a time/altitude restriction.",
  planOptionsPlans: "View trial plans for the selected aircraft.",
  planOptionsKeep: "Keep the selected aircraft in the list indefinitely;will not grey-out.\nTo remove, select the aircraft>plan options>delete.",
  planOptionsDelete: "Delete the selected aircraft from the list.\nMay be added again via the UU command",
  hold: '"Airborne holding"\nSelect an aircraft for this menu to become active.',
  holdLocation: "Fix over which the aircraft will holding.",
  holdDirection: "Direction of holding pattern relative to the holding fix.",
  holdTurns: "Direction of turns in the holding pattern.",
  holdLegLength: "Length of legs in the holding pattern.",
  holdDeleteHoldInstr: "Reset the holding fix/dir/turns/legs.",
  holdEfc: '"Expect Further Clearance Time"',
  holdDelEfc: "When this button is selected, the existing EFC time for the flight is deleted from the input box in the Hold Data Menu.",
  holdHoldBtn: "Execute/Place in hold.",
  holdHoldSpaBtn: "Execute/Place in hold and move to Special Positing Area (SPA)",
  sort:
    "Set sorting method.\nOrganizes this list in order per the selected sort method.\n\nTIPS:\n-ACL: RW controllers tend to leave this on Sector/NonSector with either Boundary Time or ACID\n\n-DEP list: RW controllers tend to use the Proposed Departure Time (P-Time) however with the nature of the simulated environment, it is suggested to not use this option.",
  sortAclSectorNonSector:
    "Sorts aircraft first by what sector has track-control for the aircraft; with your sector being above all others.\nThen the system sorts per the selected sort method below.\n\nNOTE: This is not yet simulated, as the system does not know who has track-control for an aircraft. Access to the RADAR client is required for this feature to be simulated.",
  sortAcid:
    "Sort alphabetically by callsign.\nAircraft are sorted in the Normal Posting Area in alphanumeric order based on the ACID; Aircraft in the manual positing area are not sorted by this logic, but rather by time of entry into the ACL.",
  sortBoundaryTime: "Sort ACL entries are sorted with the aircraft estimated to cross the sector boundary first at the top of the list.",
  sortConflictStatus:
    "Red alerts are displayed at the top of the list, followed by the yellow alerts, and then the airspace alerts\nWithin each alert status group, the order is determined by the alert time with the earliest alert at the top\nConflict free aircraft are sorted at the bottom.\nNOTE: Conflict Detection is not yet simulated",
  sortConflictTime:
    "ACL entries are sorted by conflict alert time, with the entry predicted to have the earliest occurring alert displayed at the top\nConflict free aircraft are sorted at the bottom of the list.\nNOTE: Conflict Detection is not yet simulated",
  sortDestination: "Sort by destination airport.",
  sortOrigin: "Sort by origin airport.",
  sortSectorBySector:
    "Sort by the aircraft's current sector.\nACL entries are sorted based on the ID of the sector that has track-control\nAircraft under the users control are at the top of the list, followed by aircraft under other sectors control\n\nNOTE: This is not yet simulated, as the system does not know who has track-control for an aircraft. Access to the RADAR client is required for this feature to be simulated",
  sortPTime: "Sort by Proposed Departure Time (P-Time)",
  postingMode:
    "Toggles between the automatic and manual posting modes for the ACL\nWhen a posting mode is selected, the title bar changes accordingly\n\nWhen Manual mode is selected, all new ACL entries are placed in the Manual Posting Area in the order in which they are received.",
  template:
    "View flight plan template\n\nNOTE: Editing this data is not yet simulated. Access to the RADAR client or FSD is required for this feature to be simulated.",
  aclCleanUp: "Cleans up the ACL by removing all entries coded gray for deletion.",
  aclHeaderPa: "Toggle number of point outs entries to display.",
  aclHeaderType: "",
  aclHeaderAlt: "",
  aclHeaderCode: "",
  aclHeaderHdg: "Show/hide assigned heading",
  aclHeaderSlash: "Show/hide assigned heading and speed",
  aclHeaderSpd: "Show/hide assigned speed",
  aclNAndVciBtn:
    'Removes the "new (N)" entry indicator and then it will toggle the voice communication indicator (VCI) with further clicks\n\nNOTE: Entry will not grey-out if the VCI is toggled on.\nThe //(AID) command will also toggle the VCI on/off.',
  aclFlightId: "Callsign",
  aclHotbox: '"Hotbox"\nLMB: opens and closes the free-text typing area\nMMB: move to spa\nRMB: toggle highlight',
  aclType: "Aircraft Type Identifier",
  aclAlt: "Assigned Altitude\n\nNOTE: Does not push assignments from vEDST to the controller client or server until we have access to these systems.",
  aclCode: "Assigned squawk/beacon code\n\nNOTE: This may not match what the aircraft is actually squawking.",
  aclHdg: "Assign heading\n\n.NOTE: Does not sync with assignments via the RADAR client until we have access.",
  aclHdgAmend: "Assign heading now.",
  aclHdgScratchpad: "Heading planned to assign in future.",
  aclHdgTurn: "Incremental left/right turn.",
  aclHdgHdg: "Heading to assign.",
  aclSpd: "Assign speed.",
  aclSpdAmend: "Assign speed now.",
  aclSpdScratchpad: "Speed planned to assign in future.",
  aclSpdKnots: "Indicated airspeed",
  aclSpdMach: "Mach number.",
  aclRemarksBtn: "LMB: toggle flight plan remarks | RMB: toggle route as displayed on VATSIM",
  aclRoute: "Open route menu",
  depHeaderType: "",
  depHeaderAlt: "",
  depHeaderCode: "",
  depCheckmarkNBtn: "Acknowledge flight plan\n\nTIP: Toggle the N to off once you have reviewed the flight plan and made any required changes.",
  depFlightId: "Callsign",
  depHotbox:
    '"Hotbox"\nLMB: opens and closes the free-text typing area.\nMMB: move to spa.\nRMB: toggle highlight.\n\nNOTE: If you highlight, input free-text information in, or place the aircraft into SPA while in the DEP list, it will transfer to the ACL the same way.',
  depType: "Aircraft Type Identifier",
  depAlt: "Assigned Altitude",
  depCode: "Assigned squawk/beacon code",
  depRoute: "Open route menu",
  plansAmend:
    "Accept trial plan result and send flight plan amendment. Will also copy fix/radial/distance (FRD) the RADAR client until we have access.",
  plansTools:
    "[NOT SIMULATED, YET]\nDisplays the Tools Menu\nThe Tools Menu allows the user to select restrictions\nThe difference between the Aircraft List and the Graphic Plan Display Tools Menu from the Plans Display Tools Menu is that the Plans Displays Tools Menu only has one available option, Restrictions.",
  plansIcao: "[NOT SIMULATED, YET]\nDisplays available International Civil Aviation Organization (ICAO) flight data for a selected entry",
  plansCleanUp: "Cancel and clear all trial plans",
  routeMenuPlanData:
    'Any actions taken while this button is selected will be sent as a trial plan only.\nTo have the action actually submitted, select "Amend" to the right.',
  routeMenuVatsimLogo:
    "Toggle the non-formatted route, as seen on VATSIM.\n\nTIP: If you have a route discontinuity [XXX], toggle the VATSIM route to see what the problem is.",
  routeMenuAmend:
    'Any actions taken while this button is selected will be sent as an actual amendment.\nTo have the action submitted as only a trial plan, select "Trial Plan" to the left.',
  routeMenuFrd: "Current location relative to a predefined reference fix in the fix/radial/distance (FRD) format.\nRMB: copy FRD to clipboard",
  routeMenuRouteInput: "Type the route manually here.",
  routeMenuPar: "[NOT SIMULATED, YET]\nInclude applicable PAR",
  routeMenuAppendStar: "[NOT SIMULATED, YET]\nOverride and ignore required PAR/PDAR routing",
  routeMenuAppendOplus: "[NOT SIMULATED, YET]\nInhibits ERR application if the box was not previously selected.",
  routeMenuDirectFix:
    "Proceed direct to this fix from current location.\nLMS on fix: will copy FRD+remaining route to the clipboard if AMEND is selected in the top right.",
  routeMenuPreferredEligible: "Show eligible preferred routes based on routing criteria.",
  routeMenuPreferredAll: "Show all known preferred routes, regardless if the aircraft meet the qualifications for the route.",
  routeMenuPreferredRoute: "Click to apply this preferred route.\n\nNOTE, this will replace the full route, not append it.",
  routeMenuFlightData: "[NOT SIMULATED, YET]",
  routeMenuPrevRoute: "Revert to previously assigned route",
  routeMenuTfmReroute: "[NOT SIMULATED, YET]",
  altMenuPlanData: "Trial Plan Only",
  altMenuAmend: "Assign Altitude Now",
  altMenuT: "Assign Altitude as Interim",
  templateMenuAid: `Aircraft Callsign/Flight Identification`,
  templateMenuNum: `Number of aircraft in this flight`,
  templateMenuSai: `Special Aircraft Indicator`,
  templateMenuTyp: `Aircraft type`,
  templateMenuEqpButton: `[NOT SIMULATED, YET]\nWhen selected, the Equipment Template is automatically displayed, pre-populated based on the stored ICAO Format of the FP.`,
  templateMenuEqpBox: `Calculated (actual) FAA Equipment Qualifier/Suffix Code`,
  templateMenuBcn: `Four-digital octal number assigning discrete or non-discrete beacon code/squawk code`,
  templateMenuSpd: `True Airspeed`,
  templateMenuFix: `"Current" fix over which the aircraft is predicted to be at a specified time.\nAKA: "Coordination Fix"`,
  templateMenuTim: `Predicted time over the coordination fix in the predicted route of flight.\n\nEXX00 = Current time.\nEXX02 = 2min from now.\nP1203 = Proposed departure time of 1203z.`,
  templateMenuAlt: `Requested/Assigned altitude`,
  templateMenuMore:
    "[NOT SIMULATED, YET]\nProvides access to the Flight Plan (More) Template. The purpose of the Flight Plan (More) Template is to display, enter or edit standard ICAO FP information that is not included in the regular Flight Plan Template.",
  templateMenuRte: `Current route of flight`,
  templateMenuCreateFp: `Create new flight plan`,
  templateMenuRmk: `Flight Plan remarks`,
  templateMenuSend: `Finalize the flight plan`,
  templateMenuExit: `Exit template`,
  equipmentTemplateMenuSurv: `Surveillance Equipment Template`,
  equipmentTemplateMenuSurv_NoXpdr: `No transponder (default selection)`,
  equipmentTemplateMenuSurv_A: `Mode A with no Mode C (Field 910b 1st character)`,
  equipmentTemplateMenuSurv_C: `Mode A with Mode C (Field 910b 1st character)`,
  equipmentTemplateMenuSurv_X: `Mode S only (Field 910b 1st character)`,
  equipmentTemplateMenuSurv_P: `Mode S and pressure altitude (Field 910b 1st character)`,
  equipmentTemplateMenuSurv_I: `Mode S and ACID transmission (Field 910b 1st character)`,
  equipmentTemplateMenuSurv_S: `Mode S and ACID and pressure altitude (Field 910b 1st character)`,
  equipmentTemplateMenuSurv_H: `Mode S and ACID transmission and enhanced surveillance`,
  equipmentTemplateMenuSurv_L: `Mode S and pressure altitude and enhanced surveillance`,
  equipmentTemplateMenuSurv_E: `Mode S and pressure altitude and extended squitter`,
  equipmentTemplateMenuSurv_No1090: `No 1090 ADS-B equipage (default selection)`,
  equipmentTemplateMenuSurv_B1: `Dedicated 1090 MHz ADS-B OUT`,
  equipmentTemplateMenuSurv_B2: `Dedicated 1090 MHz ADS-B IN/OUT`,
  equipmentTemplateMenuSurv_NoUat: `No UAT equipage (default selection)`,
  equipmentTemplateMenuSurv_U1: `UAT OUT`,
  equipmentTemplateMenuSurv_U2: `UAT IN/OUT`,
  equipmentTemplateMenuSurv_NoVdl: `No VDL Mode 4 equipage (default selection)`,
  equipmentTemplateMenuSurv_V1: `VDL Mode 4 OUT`,
  equipmentTemplateMenuSurv_V2: `VDL Mode 4 IN/OUT`,
  equipmentTemplateMenuSurv_260b: `1090 Certification`,
  equipmentTemplateMenuSurv_262b: `UAL Certification`,
  equipmentTemplateMenuSurv_Sur: `Surveillance equipment data (Field 918)`,
  equipmentTemplateMenuSurv_Ok: `Equipment Template is removed and the Template (Flight Plan or Amendment) is updated and displayed such that the equipment qualifier text entry box cannot be edited (grayed out) and the cursor rests over the Send button.`,
  equipmentTemplateMenuSurv_Reset: `Changes to the template are discarded and the displayed data reverts to its initial state.`,
  equipmentTemplateMenuSurv_Cancel: `Equipment Template is removed, the changes (if any) are not retained, and the Template (Flight Plan or Amendment) is displayed with the cursor positioned over the Exit button.`,
  equipmentTemplateMenuNAV: `Navigation (NAV) Equipment Template`,
  equipmentTemplateMenuNAV_F: `Automatic Direction Finding (ADF) System`,
  equipmentTemplateMenuNAV_O: `Very High Frequency Omni-directional (radio) Range (VOR)`,
  equipmentTemplateMenuNAV_D: `Distance Measuring Equipment (DME)`,
  equipmentTemplateMenuNAV_T: `Tactical Air Navigation (TACAN)`,
  equipmentTemplateMenuNAV_G: `Global Positioning System (GPS)/Global Navigation Satellite System (GNSS)`,
  equipmentTemplateMenuNAV_I: `Internal Navigational System (INS)`,
  equipmentTemplateMenuNAV_C: `Long Range Navigation (LORAN C)`,
  equipmentTemplateMenuNAV_R: `Required Navigation Performance (RNP)`,
  equipmentTemplateMenuNAV_X: `Minimum Navigation Performance Specification Airspace (MNPS)`,
  equipmentTemplateMenuNAV_Rnav: `Area Navigation. This is the default setting for the RNAV/RNP boxes. The radio button is not displayed if RNP is not adapted, but the RNAV label remains. When the RNAV radio button is selected, all of the fields are processed as RNAV.`,
  equipmentTemplateMenuNAV_Rnp: `Required Navigational Performance. The aircraft has on-board monitoring of RNAV. The radio button and label are displayed when adapted. When the RNP radio button is selected, all of the fields are processed as RNP.`,
  equipmentTemplateMenuNAV_RnavRnpFields: `These fields accept numeric input from 0 to 99.99 in the format of:\n(d)d(.d(d)).`,
  equipmentTemplateMenuNAV_W: `Reduced Vertical Separation Minimum (RVSM)`,
  equipmentTemplateMenuNAV_Nav: `Navigation equipment data. This is the active input box when the template is opened. (Field 918)`,
  equipmentTemplateMenuNAV_Ok: `Equipment Template is removed and the Template (Flight Plan or Amendment) is updated and displayed such that the equipment qualifier text entry box cannot be edited (grayed out) and the cursor rests over the Send button.`,
  equipmentTemplateMenuNAV_Reset: `Changes to the template are discarded and the displayed data reverts to its initial state.`,
  equipmentTemplateMenuNAV_Cancel: `Equipment Template is removed, the changes (if any) are not retained, and the Template (Flight Plan or Amendment) is displayed with the cursor positioned over the Exit button.`,
  equipmentTemplateMenuComm: `Communication Equipment Template`,
  equipmentTemplateMenuComm_H: `High Frequency Communications (HF) (Field 910a)`,
  equipmentTemplateMenuComm_V: `Very High Frequency (VHF) (Field 910a)`,
  equipmentTemplateMenuComm_U: `Ultrahigh Frequency (UHF) (Field 910a)`,
  equipmentTemplateMenuComm_Y: `8.33 kHZ (Field 910a)`,
  equipmentTemplateMenuComm_J1: `ATN VDL MODE 2 (Field 910a)`,
  equipmentTemplateMenuComm_J2: `FANS1/A HF (Field 910a)`,
  equipmentTemplateMenuComm_J3: `FANS1/A VDL MODE A (Field 910a)`,
  equipmentTemplateMenuComm_J4: `FANS1/A VDL MODE 2 (Field 910a)`,
  equipmentTemplateMenuComm_J5: `FANS1/A INMARSAT (Field 910a)`,
  equipmentTemplateMenuComm_J6: `FANS1/A MTSAT (Field 910a)`,
  equipmentTemplateMenuComm_J7: `FANS1/A IRIDIUM (Field 910a)`,
  equipmentTemplateMenuComm_E1: `FMCWPR (Field 910a)`,
  equipmentTemplateMenuComm_E2: `D-FIS (Field 910a)`,
  equipmentTemplateMenuComm_E3: `PDC (Field 910a)`,
  equipmentTemplateMenuComm_M1: `INMARSAT`,
  equipmentTemplateMenuComm_M2: `MTSTAT`,
  equipmentTemplateMenuComm_M3: `IRIDIUM`,
  equipmentTemplateMenuComm_Dat: `Data related to data link capability (Field 918)`,
  equipmentTemplateMenuComm_Com: `Communications equipment data (Field 918a)`,
  equipmentTemplateMenuComm_Ok: `Equipment Template is removed and the Template (Flight Plan or Amendment) is updated and displayed such that the equipment qualifier text entry box cannot be edited (grayed out) and the cursor rests over the Send button.`,
  equipmentTemplateMenuComm_Reset: `Changes to the template are discarded and the displayed data reverts to its initial state.`,
  equipmentTemplateMenuComm_Cancel: `Equipment Template is removed, the changes (if any) are not retained, and the Template (Flight Plan or Amendment) is displayed with the cursor positioned over the Exit button.`,
  equipmentTemplateMenuAppServ: `Approach and Services`,
  equipmentTemplateMenuAppServ_L: `Instrument Landing System (ILS) (Field 910a)`,
  equipmentTemplateMenuAppServ_K: `Microwave Landing System (MLS) (Field 910a)`,
  equipmentTemplateMenuAppServ_A: `Ground Based Augmentation System (GBAS) Landing System (Field 910a)`,
  equipmentTemplateMenuAppServ_B: `Localizer Performance with Vertical Guidance (LPV) (Field 910a)`,
  equipmentTemplateMenuAppServ_S: `Standard (Field 910a)`,
  equipmentTemplateMenuAppServ_Ok: `Equipment Template is removed and the Template (Flight Plan or Amendment) is updated and displayed such that the equipment qualifier text entry box cannot be edited (grayed out) and the cursor rests over the Send button.`,
  equipmentTemplateMenuAppServ_Reset: `Changes to the template are discarded and the displayed data reverts to its initial state.`,
  equipmentTemplateMenuAppServ_Cancel: `Equipment Template is removed, the changes (if any) are not retained, and the Template (Flight Plan or Amendment) is displayed with the cursor positioned over the Exit button.`
};
