export const Tooltips = {
  mca: 'accepts edst commands',
  ra: 'shows response to certain commands',
  acl: '"Aircraft List", showing all active flights',
  dep: '"Departure List", showing all proposed departures',
  plans: 'trial plans',
  status_active: 'edst system status',
  status_outage: 'list of inactive/malfunctioning systems',
  plan_options: 'options for manipulating FP data',
  plan_options_alt: 'trial plan or amend assigned altitude',
  plan_options_speed: 'trial plan or amend assigned speed',
  plan_options_route: 'trial plan or amend assigned routing',
  plan_options_prev_route: 'revert to previously assigned routing',
  plan_options_stop_probe: 'stop conflict probing',
  plan_options_trial_restr: 'trial plan a time/altitude restriction',
  plan_options_plans: 'view trial plans for the selected aircraft',
  plan_options_keep: 'keep the selected aircraft in the list indefinitely',
  plan_options_delete: 'delete the selected aircraft from the list',
  hold: 'airborne holding',
  hold_location: 'fix over which the aircraft is holding',
  hold_direction: 'direction from the fix where the aircraft will hold',
  hold_turns: 'direction of turns in the holding pattern',
  hold_leg_length: 'length of legs in the holding pattern',
  hold_delete_hold_instr: 'reset the holding fix/dir/turns/legs',
  hold_efc: 'expect further clearance time',
  hold_del_efc: 'reset efc time to default interval',
  hold_hold_btn: 'execute hold',
  hold_hold_spa_btn: 'execute hold and move to spa',
  sort: 'set sorting method',
  sort_acl_sector_non_sector: 'show aircraft in this sector above all other aircraft',
  sort_acid: 'sort alphabetically by callsign',
  sort_boundary_time: 'sort by time until reaching this sector\'s airspace',
  sort_conflict_status: 'sort by number of alerts',
  sort_conflict_time: 'sort by time of soonest alert',
  sort_destination: 'sort by destination airport',
  sort_origin: 'sort by origin airport',
  sort_sector_by_sector: 'sort by the aircraft\'s current sector',
  sort_p_time: 'sort by P-time',
  posting_mode: 'change posting mode between manual/automatic',
  template: 'view flight plan template',
  acl_clean_up: 'remove all stale entries',
  acl_header_pa: 'number of point outs to show',
  acl_header_type: '',
  acl_header_alt: '',
  acl_header_code: '',
  acl_header_hdg: 'show/hide assigned heading',
  acl_header_slash: 'show/hide assigned heading/speed',
  acl_header_spd: 'show/hide assigned speed',
  acl_wifi_button: 'voice communication indicator (VCI)',
  acl_flight_id: 'callsign',
  acl_spa_button: 'LMB: scratchpad | MMB: move to spa | RMB: toggle highlight',
  acl_type: 'aircraft type identifier',
  acl_alt: 'assigned altitude',
  acl_code: 'assigned squawk code',
  acl_hdg: 'assign heading',
  acl_hdg_amend: 'assign heading now',
  acl_hdg_scratchpad: 'heading planned to assign in future',
  acl_hdg_turn: 'incremental left/right turn',
  acl_hdg_hdg: 'heading to assign',
  acl_spd: 'assign speed',
  acl_spd_amend: 'assign speed now',
  acl_spd_scratchpad: 'speed planned to assign in future',
  acl_spd_knots: 'indicated airspeed',
  acl_spd_mach: 'mach number',
  acl_remark_btn: 'toggle flight plan remarks',
  acl_route: 'open route menu',
  dep_header_type: '',
  dep_header_alt: '',
  dep_header_code: '',
  dep_checkmark_box: 'acknowledge flight plan',
  dep_flight_id: 'callsign',
  dep_spa_button: 'LMB: scratchpad | MMB: move to spa | RMB: toggle highlight',
  dep_type: 'aircraft type identifier',
  dep_alt: 'assigned altitude',
  dep_code: 'assigned squawk code',
  dep_route: 'open route menu',
  plans_amend: 'accept trial plan result and send flight plan amendment',
  plans_interim: '',
  plans_tools: '',
  plans_icao: '',
  plans_clean_up: 'cancel all trial plans',
  route_menu_trial_plan: 'trial plan only',
  route_menu_vatsim_logo: 'toggle full vatsim route',
  route_menu_amend: 'apply route amendment now',
  route_menu_frd: 'current location fix/radial/distance',
  route_menu_route_input: 'route to assign',
  route_menu_par: 'include applicable PAR',
  route_menu_append_star: 'override and ignore required PAR/PDAR routing',
  route_menu_append_oplus: '',
  route_menu_direct_fix: 'proceed direct to fix',
  route_menu_preferred_eligible: 'show eligible preferred routes',
  route_menu_preferred_all: 'show all known preferred routes',
  route_menu_preferred_route: 'click to apply this preferred route',
  route_menu_flight_data: '',
  route_menu_prev_route: 'revert to previously assigned route',
  route_menu_tfm_reroute: '',
  alt_menu_trial_plan: 'trial plan only',
  alt_menu_amend: 'assign altitude now',
  alt_menu_header_t: 'assign altitude as interim'
};