name: Build and Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Get version'
        id: version
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: 'Format version number'
        id: version-number
        run: |
          VERSION=${{ steps.version.outputs.tag }}
          echo "VERSION_NUMBER=${VERSION#v}" >> $GITHUB_OUTPUT
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: dist
        env:
          VITE_VNAS_CONFIG_URL: https://configuration.vnas.vatsim.net/
          VITE_VNAS_ENV_NAME: Test
          VITE_PROD_VATSIM_CLIENT_ID: ${{secrets.VATSIM_CLIENT_ID}}
          VITE_PROD_DOMAIN: https://edst.virtualnas.net
          VITE_SHARED_STATE_URL: https://tdls.oakartcc.org
          VITE_SHARED_STATE_AUTH_KEY: ${{secrets.SHARED_STATE_AUTH_KEY}}
          VITE_BACKEND_BASEURL: https://edst-api.k0rg.org/api
          VITE_VERSION: ${{ steps.version-number.outputs.VERSION_NUMBER }}
        run: npm run build
      - name: Archive build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Add known host
        run: echo '${{ secrets.KNOWN_HOSTS }}' >> ~/.ssh/known_hosts
      - name: Deploy to server
        run: rsync -avz --delete --exclude=docs --exclude=downloads . ${{secrets.USER}}@${{secrets.HOST}}:/var/www/edst.virtualnas.net/wwwroot
